baseurl = "https://www.progz.nl/blog/"
languagecode = "en"
defaultcontentlanguage = "en"

title = "Rogier's blog"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

# canonifyurls = true

[params]
    author = "Rogier Reedijk"
    info = "Full Stack .NET developer"
    #description = "Rogier Reedijk's personal website"
    authorimage = "img/Rogier-Reedijk.jpg"
    dateformat = "Jan 2, 2006"
    themeColor = "theme-progz"
    mainSections = ["post"]

    # sidebar, copyright & license
    copyright = "Rogier Reedijk"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances or Staticman
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark
    enableStaticmanComments = true

    # Table of contents
    #toc = none, "hugo", or "tocbot"
    postNavigation = true
    relatedPosts = false #look at enabling includeNewer first: https://gohugo.io/content-management/related

## comment settings
[params.staticman]
  # Sets Statiman to be active
  staticman = true
  #api      = "http://localhost:7071/api/PostComment"
  api       = "https://static-comments-to-git.azurewebsites.net/api/PostComment"
  akismet   = true

[params.staticman.recaptcha]
  sitekey = "6LegB4YUAAAAAJTBaaLSIIKgByn1psZ4vcr1sTMV"

## Social Accounts
[params.social]
    github = "xs4free"
    #instagram = "<username>"
    #xing = "<username>"
    linkedin = "rogierreedijk"
    twitter = "xs4free"
    facebook = "rogier.reedijk"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    #email = "home-automation@progz.nl"
    # gravatar = "your-email@example.com"

## Main Menu
# [[menu.main]]
#     name = "Posts"
#     weight = 100
#     identifier = "posts"
#     url = "/posts/"
# [[menu.main]]
#     name = "Portfolio"
#     identifier = "portfolio"
#     weight = 200
#     url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
